# This is a basic workflow that is manually triggered

name: Build Any Apps

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      repo:
        type: choice
        description: Repository
        options:
        - zikalino/esp-idf
        - espressif/esp-idf
      branch:
        description: Branch
        type: string
        default: master
      folders:
        description: Folders
        type: string
        default: "['examples/system/efuse']"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  container:
    strategy:
      matrix:
        folder: ${{ fromJSON( inputs.folders )}}
    runs-on: ubuntu-latest
    container:
      image: zimkal/esp-qemu-1
      options: --user root
    steps:
      - name: Info
        run: |
          echo "====================== INFORMATION"
          whoami
          echo ~
          ls /root
          ls /root/.espressif
          cp -R /root/.espressif ~
          echo "====================== COPIED"
          ls ~/.espressif
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: esp-idf
      - name: Install Tools
        run: |
          export IDF_PATH=/__w/actions/actions/esp-idf
          cd /__w/actions/actions/esp-idf
          ./install.sh all
      - name: Build ${{ matrix.folder }}
        run: |
          export IDF_PATH=/__w/actions/actions/esp-idf
          cd /__w/actions/actions/esp-idf
          . ./export.sh
          python3 ./tools/idf_tools.py install-python-env --features pytest,ci
          # python3 /__w/actions/actions/esp-idf/tools/ci/ci_build_apps.py -v -t ${{ matrix.target }} --pytest-apps --collect-size-info size_info.txt components/${{ matrix.component }} 2>&1 | tee -a out.txt
          python3 /__w/actions/actions/esp-idf/tools/ci/ci_build_apps.py -v --pytest-apps --collect-size-info size_info.txt ${{ matrix.folder }}
          echo "========================================= BUILD OUTPUT"
          # cat out.txt
